version: '3.8'

services:
  snipeit-db:
    image: mariadb
    container_name: snipeit-db
    environment:
      MYSQL_ROOT_PASSWORD: snipeit
      MYSQL_DATABASE: snipeit
      MYSQL_USER: snipeit
      MYSQL_PASSWORD: snipeit
    volumes:
      - ./snipeit-db:/var/lib/mysql
    ports:
      - '3306:3306'

  snipeit-app:
    image: linuxserver/snipe-it:latest
    container_name: snipeit-app
    depends_on:
      - snipeit-db
    env_file: .env
    volumes:
      - ./config:/config
    ports:
      - '8080:80'
